# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

RC=/home/cassepipe/.cargo/bin/rustc
DC=/usr/bin/gdc
AS=/usr/bin/gcc
MM=/usr/bin/gcc
CXX=/usr/bin/gcc
MXX=/usr/bin/gcc
CU=/usr/bin/clang
CC=/usr/bin/gcc

AR=/usr/bin/ar
DCAR=/usr/bin/gcc-ar
RCAR=/home/cassepipe/.cargo/bin/rustc
SH=/usr/bin/g++
DCSH=/usr/bin/gdc
RCSH=/home/cassepipe/.cargo/bin/rustc
LD=/usr/bin/g++
DCLD=/usr/bin/gdc
RCLD=/home/cassepipe/.cargo/bin/rustc

exe_CXXFLAGS=-m64 -std=c++98 -Wall -Wextra -g3
exe_LDFLAGS=-m64

default:  exe

all:  exe

.PHONY: default all  exe

exe: ./linux/x86_64/release/exe
./linux/x86_64/release/exe: ./.objs/exe/linux/x86_64/release/ConfigParser.cpp.o ./.objs/exe/linux/x86_64/release/VirtServ.cpp.o ./.objs/exe/linux/x86_64/release/main.cpp.o
	@echo linking.release exe
	@mkdir -p ./linux/x86_64/release
	@$(LD) -o ./linux/x86_64/release/exe ./.objs/exe/linux/x86_64/release/ConfigParser.cpp.o ./.objs/exe/linux/x86_64/release/VirtServ.cpp.o ./.objs/exe/linux/x86_64/release/main.cpp.o $(exe_LDFLAGS) > ./.build.log 2>&1

./.objs/exe/linux/x86_64/release/ConfigParser.cpp.o: ConfigParser.cpp
	@echo compiling.release ConfigParser.cpp
	@mkdir -p ./.objs/exe/linux/x86_64/release
	@$(CXX) -c $(exe_CXXFLAGS) -o ./.objs/exe/linux/x86_64/release/ConfigParser.cpp.o ConfigParser.cpp > ./.build.log 2>&1

./.objs/exe/linux/x86_64/release/VirtServ.cpp.o: VirtServ.cpp
	@echo compiling.release VirtServ.cpp
	@mkdir -p ./.objs/exe/linux/x86_64/release
	@$(CXX) -c $(exe_CXXFLAGS) -o ./.objs/exe/linux/x86_64/release/VirtServ.cpp.o VirtServ.cpp > ./.build.log 2>&1

./.objs/exe/linux/x86_64/release/main.cpp.o: main.cpp
	@echo compiling.release main.cpp
	@mkdir -p ./.objs/exe/linux/x86_64/release
	@$(CXX) -c $(exe_CXXFLAGS) -o ./.objs/exe/linux/x86_64/release/main.cpp.o main.cpp > ./.build.log 2>&1

clean:  clean_exe

clean_exe: 
	@rm -rf ./linux/x86_64/release/exe
	@rm -rf ./linux/x86_64/release/exe.sym
	@rm -rf ./.objs/exe/linux/x86_64/release/ConfigParser.cpp.o
	@rm -rf ./.objs/exe/linux/x86_64/release/VirtServ.cpp.o
	@rm -rf ./.objs/exe/linux/x86_64/release/main.cpp.o

